
package com.jax.Servire;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* IserviceImplService service = new IserviceImplService();
* IserviceImplDelegate portType = service.getIserviceImplPort();
* portType.login(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "IserviceImplService", targetNamespace = "http://DataService/", wsdlLocation = "http://127.0.0.1:8080/DataService/IserviceImplPort?wsdl")
public class IserviceImplService extends Service {

	private final static URL ISERVICEIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.jax.Servire.IserviceImplService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.jax.Servire.IserviceImplService.class.getResource(".");
			url = new URL(baseUrl, "http://127.0.0.1:8080/DataService/IserviceImplPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/DataService/IserviceImplPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ISERVICEIMPLSERVICE_WSDL_LOCATION = url;
	}

	public IserviceImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public IserviceImplService() {
		super(ISERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://DataService/", "IserviceImplService"));
	}

	/**
	 * 
	 * @return returns IserviceImplDelegate
	 */
	@WebEndpoint(name = "IserviceImplPort")
	public IserviceImplDelegate getIserviceImplPort() {
		return super.getPort(new QName("http://DataService/", "IserviceImplPort"), IserviceImplDelegate.class);
	}

}
