
package com.jax.Servire;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IserviceImplDelegate", targetNamespace = "http://DataService/")
public interface IserviceImplDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Login")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Login", targetNamespace = "http://DataService/", className = "com.jax.Servire.Login")
	@ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://DataService/", className = "com.jax.Servire.LoginResponse")
	public String login(@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Excute")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "Excute", targetNamespace = "http://DataService/", className = "com.jax.Servire.Excute")
	@ResponseWrapper(localName = "ExcuteResponse", targetNamespace = "http://DataService/", className = "com.jax.Servire.ExcuteResponse")
	public String excute(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
